theme: jekyll-theme-merlot
title: Bine ati venit pe siteul meu 

description: feel free to bookmark me- aici am modificat in branch 2 sa vad cum merge daca ai mai multe ramuri
=======
description: feel free to bookmark me- aici am modificat in branch 1 sa vad cum merge- modific iar in ramura 1 sa vad difernetele

